---
# Defines tasks for Debian/Ubuntu installation

- name: Install packages
  apt: >
    name="{{ item }}"
    update_cache=yes
    cache_valid_time=86400
    state=latest
  with_items: "{{ security_updates_packages }}"
  tags:
    - security
